version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8088:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - database

  database:
    image: mysql:8.0.23
    ports:
      - '33064:3306'
    environment:
      - "MYSQL_DATABASE=survey_system"
      - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local